using System.Net;
using System.Text;
using TechieRag.Web;
using Xunit;

namespace TechieRag.Tests.Web;

/// <summary>
/// REQ-RAG-018 / BRD-62: how the transcript reader copes with the shapes real watch pages take.
/// </summary>
/// <remarks>
/// <para>Every fixture here is trimmed from a page YouTube actually served on 2026-07-27, not from
/// an idea of what one looks like. That distinction is the whole reason the original caption-track
/// extraction was wrong: a hand-written fixture used the <c>simpleText</c> shape, real pages also
/// use the <c>runs</c> shape, and only the second one broke it.</para>
/// <para>The live canary lives in <c>Web/Live/LiveYouTubeTranscriptTests</c>. These tests cannot
/// tell you whether YouTube has changed; they can only stop a change here from re-breaking what has
/// already been diagnosed once.</para>
/// </remarks>
public sealed class YouTubeTranscriptReaderTests
{
    private const string TrackUrl = "https://www.youtube.com/api/timedtext?v=abcdefghijk&lang=en";

    /// <summary>
    /// A caption track whose name is a <c>runs</c> array — which contains a nested <c>]</c> — is
    /// still found.
    /// </summary>
    /// <remarks>
    /// THE regression. The extraction was <c>"captionTracks":(\[.*?\])</c>, and a lazy match stops
    /// at the first <c>]</c>. With the <c>runs</c> shape that bracket is inside the first element, so
    /// the match returned a fragment, the fragment failed to parse, and a video with a full set of
    /// caption tracks was reported as having none.
    /// </remarks>
    [Fact]
    public async Task CaptionTrackWithNestedRunsArrayIsStillFound()
    {
        var page = WatchPage(
            """
            "captionTracks":[{"baseUrl":"TRACKURL","name":{"runs":[{"text":"English"}]},
            "languageCode":"en","isTranslatable":true}]
            """);

        var transcript = await Read(page);

        Assert.Contains("Vectors are just lists of numbers", transcript.Text, StringComparison.Ordinal);
    }

    /// <summary>The long-standing <c>simpleText</c> shape keeps working.</summary>
    [Fact]
    public async Task CaptionTrackWithSimpleTextNameIsFound()
    {
        var page = WatchPage(
            """
            "captionTracks":[{"baseUrl":"TRACKURL","name":{"simpleText":"English"},"languageCode":"en"}]
            """);

        var transcript = await Read(page);

        Assert.Contains("Vectors are just lists of numbers", transcript.Text, StringComparison.Ordinal);
    }

    /// <summary>
    /// A bracket inside a <c>baseUrl</c> does not end the array early.
    /// </summary>
    /// <remarks>
    /// Bracket counting alone is not enough — it has to skip string literals, because a signed
    /// timed-text URL is arbitrary text and may legitimately carry one.
    /// </remarks>
    [Fact]
    public async Task BracketInsideATrackUrlDoesNotTruncateTheArray()
    {
        var page = WatchPage(
            """
            "captionTracks":[{"baseUrl":"TRACKURL&sig=a]b","name":{"simpleText":"English"},"languageCode":"en"}]
            """);

        var transcript = await Read(page, trackUrl: TrackUrl + "&sig=a]b");

        Assert.Contains("Vectors are just lists of numbers", transcript.Text, StringComparison.Ordinal);
    }

    /// <summary>
    /// A manual track is preferred over the auto-generated one in the same language.
    /// </summary>
    /// <remarks>
    /// ASR output has no sentence punctuation and chunk boundaries follow punctuation, so choosing
    /// the machine track when a human one exists measurably degrades retrieval.
    /// </remarks>
    [Fact]
    public async Task ManualTrackIsPreferredOverAutoGeneratedInTheSameLanguage()
    {
        var page = WatchPage(
            """
            "captionTracks":[{"baseUrl":"https://asr.test/track","name":{"runs":[{"text":"English (auto)"}]},
            "languageCode":"en","kind":"asr"},
            {"baseUrl":"TRACKURL","name":{"runs":[{"text":"English"}]},"languageCode":"en"}]
            """);

        var requested = new List<string>();
        var transcript = await Read(page, recordRequests: requested);

        Assert.Contains("Vectors are just lists of numbers", transcript.Text, StringComparison.Ordinal);
        Assert.DoesNotContain(requested, url => url.Contains("asr.test", StringComparison.Ordinal));
    }

    /// <summary>
    /// A caption track served as an empty body is reported as a YouTube restriction, not as a video
    /// without captions.
    /// </summary>
    /// <remarks>
    /// This is what live YouTube does today for every video (TR-RAG-015). Blaming the video sends the
    /// operator off to try a different one, which will fail identically.
    /// </remarks>
    [Fact]
    public async Task EmptyCaptionTrackIsReportedAsARestrictionRatherThanAsAMissingTranscript()
    {
        var page = WatchPage(
            """
            "captionTracks":[{"baseUrl":"TRACKURL","name":{"simpleText":"English"},"languageCode":"en"}]
            """);

        var error = await Assert.ThrowsAsync<WebFetchException>(
            () => Read(page, trackBody: string.Empty));

        Assert.Contains("served it empty", error.Message, StringComparison.OrdinalIgnoreCase);
        Assert.Contains("nothing was ingested", error.Message, StringComparison.OrdinalIgnoreCase);
    }

    /// <summary>
    /// A watch page carrying player data but no caption list is reported as a video without captions.
    /// </summary>
    [Fact]
    public async Task VideoWithPlayerDataButNoCaptionListIsReportedAsHavingNoCaptions()
    {
        var page = WatchPage("\"ytInitialPlayerResponse\":{\"videoDetails\":{}}");

        var error = await Assert.ThrowsAsync<WebFetchException>(() => Read(page));

        Assert.Contains("no captions", error.Message, StringComparison.OrdinalIgnoreCase);
    }

    /// <summary>
    /// A watch page with no player data at all is reported as a consent or bot check.
    /// </summary>
    /// <remarks>
    /// Observed live: the same video returns a full player page on one request and a stripped page on
    /// the next. Calling the stripped one "this video has no captions" is a false statement about the
    /// video, and it sends the operator looking in the wrong place.
    /// </remarks>
    [Fact]
    public async Task WatchPageWithoutPlayerDataIsReportedAsAConsentOrBotCheck()
    {
        var page = "<html><head><title>Before you continue - YouTube</title></head><body></body></html>";

        var error = await Assert.ThrowsAsync<WebFetchException>(() => Read(page));

        Assert.Contains("no player data", error.Message, StringComparison.OrdinalIgnoreCase);
        Assert.Contains("consent", error.Message, StringComparison.OrdinalIgnoreCase);
    }

    private static string WatchPage(string playerJson) =>
        "<html><head><title>A Talk About Vectors - YouTube</title></head>"
        + "<body><script>var ytInitialPlayerResponse = {" + playerJson + "};</script></body></html>";

    private static Task<YouTubeTranscript> Read(
        string page,
        string? trackUrl = null,
        string? trackBody = null,
        List<string>? recordRequests = null)
    {
        var resolvedTrackUrl = trackUrl ?? TrackUrl;
        var body = trackBody ?? """
            <transcript>
              <text start="0" dur="2">Vectors are just lists of numbers.</text>
              <text start="2" dur="3">The interesting part is what the distances mean.</text>
            </transcript>
            """;

        var handler = new ScriptedHandler(
            page.Replace("TRACKURL", resolvedTrackUrl.Replace("&", "\\u0026", StringComparison.Ordinal), StringComparison.Ordinal),
            body,
            recordRequests);

        return new YouTubeTranscriptReader(new HttpClient(handler))
            .ReadAsync("https://www.youtube.com/watch?v=abcdefghijk");
    }

    /// <summary>Serves the watch page for the watch URL and the caption body for anything else.</summary>
    private sealed class ScriptedHandler : HttpMessageHandler
    {
        private readonly string watchPage;
        private readonly string trackBody;
        private readonly List<string>? requests;

        public ScriptedHandler(string watchPage, string trackBody, List<string>? requests)
        {
            this.watchPage = watchPage;
            this.trackBody = trackBody;
            this.requests = requests;
        }

        protected override Task<HttpResponseMessage> SendAsync(
            HttpRequestMessage request, CancellationToken cancellationToken)
        {
            var url = request.RequestUri!.ToString();
            requests?.Add(url);

            var isWatchPage = request.RequestUri.AbsolutePath.Contains("watch", StringComparison.Ordinal);
            var body = isWatchPage ? watchPage : trackBody;

            return Task.FromResult(new HttpResponseMessage(HttpStatusCode.OK)
            {
                Content = new StringContent(body, Encoding.UTF8, isWatchPage ? "text/html" : "text/xml"),
                RequestMessage = request,
            });
        }
    }
}
