-- 0001-InitialSchema (PostgreSQL) — TechieDesk P1 app-owned schema (BRD-104).
-- Mirror of Scripts/Sqlite/0001-InitialSchema.sql; must stay schema-equivalent.
-- Identifiers are quoted to preserve PascalCase per docs/TechieRag-Coding-Standards.md
-- (Postgres lower-cases unquoted identifiers). The TechieRag library self-manages
-- its own Tr* tables; they are NOT created here.

CREATE TABLE IF NOT EXISTS "WorkspaceAssignment" (
    "WorkspaceAssignmentId" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "WorkspaceId"           TEXT NOT NULL,
    "UserId"                TEXT NOT NULL,
    "RoleName"              TEXT NOT NULL,
    "CreatedAt"             TIMESTAMPTZ NOT NULL,
    CONSTRAINT "PkWorkspaceAssignment" PRIMARY KEY ("WorkspaceAssignmentId"),
    CONSTRAINT "UcWorkspaceAssignmentWorkspaceIdUserId" UNIQUE ("WorkspaceId", "UserId")
);

CREATE INDEX IF NOT EXISTS "IXWorkspaceAssignmentUserId" ON "WorkspaceAssignment" ("UserId");

CREATE TABLE IF NOT EXISTS "InstanceSetting" (
    "SettingKey"   TEXT NOT NULL,
    "SettingValue" TEXT NOT NULL,
    "UpdatedAt"    TIMESTAMPTZ NOT NULL,
    CONSTRAINT "PkInstanceSetting" PRIMARY KEY ("SettingKey")
);

CREATE TABLE IF NOT EXISTS "EventLog" (
    "EventLogId" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "OccurredAt" TIMESTAMPTZ NOT NULL,
    "Category"   TEXT NOT NULL,
    "Actor"      TEXT NOT NULL,
    "EventName"  TEXT NOT NULL,
    "Detail"     TEXT NULL,
    "Source"     TEXT NULL,
    CONSTRAINT "PkEventLog" PRIMARY KEY ("EventLogId")
);

CREATE INDEX IF NOT EXISTS "IXEventLogOccurredAt" ON "EventLog" ("OccurredAt");
CREATE INDEX IF NOT EXISTS "IXEventLogCategory" ON "EventLog" ("Category");

CREATE TABLE IF NOT EXISTS "GdprRequest" (
    "GdprRequestId" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "UserId"        TEXT NOT NULL,
    "RequestType"   TEXT NOT NULL,
    "Status"        TEXT NOT NULL,
    "RequestedAt"   TIMESTAMPTZ NOT NULL,
    CONSTRAINT "PkGdprRequest" PRIMARY KEY ("GdprRequestId")
);

CREATE INDEX IF NOT EXISTS "IXGdprRequestUserId" ON "GdprRequest" ("UserId");

CREATE TABLE IF NOT EXISTS "LicenseCache" (
    "LicenseCacheId" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "UserId"         TEXT NOT NULL,
    "PayloadJson"    TEXT NOT NULL,
    "ValidatedAt"    TIMESTAMPTZ NOT NULL,
    CONSTRAINT "PkLicenseCache" PRIMARY KEY ("LicenseCacheId"),
    CONSTRAINT "UcLicenseCacheUserId" UNIQUE ("UserId")
);
